stages:
  # data_ingestion:
  #   cmd: python src/components/1_data_ingestion.py
  #   deps:
  #     - src/utils.py
  #     - src/config/configuration_manager.py
  #     - src/entity/entity_config.py
  #     - Secrets/Bundles/secure-connect-scania-truck-failure-1.zip
  #     - Secrets/Bundles/secure-connect-scania-truck-failure-train-2.zip
  #     - Secrets/Bundles/secure-connect-scania-truck-failure-train-3.zip
  #     - Secrets/Bundles/Test Data Bundles/secure-connect-scania-truck-failure-test1.zip
  #     - Secrets/Bundles/Test Data Bundles/secure-connect-scania-truck-failure-test2.zip
  #     - Secrets/Bundles/Test Data Bundles/secure-connect-scania-truck-failure-test3.zip
  #     - Secrets/Tokens/scania_truck_failure_1-token.json
  #     - Secrets/Tokens/scania_truck_failure_train_2-token.json
  #     - Secrets/Tokens/scania_truck_failure_train_3-token.json
  #     - Secrets/Tokens/Test Data Tokens/scania_truck_failure_test1-token.json
  #     - Secrets/Tokens/Test Data Tokens/scania_truck_failure_test2-token.json
  #     - Secrets/Tokens/Test Data Tokens/scania_truck_failure_test3-token.json
  #   outs:
  #     - artifacts/data/raw/train_data_1.csv
  #     - artifacts/data/raw/train_data_2.csv
  #     - artifacts/data/raw/train_data_3.csv
  #     - artifacts/data/raw/test_data_1.csv
  #     - artifacts/data/raw/test_data_2.csv
  #     - artifacts/data/raw/test_data_3.csv
  
  stage_1_processing:
    cmd: python src/components/2_stage_1_preprocessing.py
    deps: 
      - src/components/1_data_ingestion.py
      - artifacts/data/raw/train_data_1.csv
      - artifacts/data/raw/train_data_2.csv
      - artifacts/data/raw/train_data_3.csv
      - artifacts/data/raw/test_data_1.csv
      - artifacts/data/raw/test_data_2.csv
      - artifacts/data/raw/test_data_3.csv
    # outs: 
    #   - artifacts/data/processed/stage_1_processing/preprocessed_test_data.csv
    #   - artifacts/data/processed/stage_1_processing/preprocessed_train_data.csv

  data_splitting:
    cmd: python src/components/3_data_split.py
    deps: 
      - src/components/2_stage_1_preprocessing.py
      - artifacts/data/processed/stage_1_processing/preprocessed_train_data.csv
    # outs:
    #   - artifacts/data/train_test/train.csv
    #   - artifacts/data/train_test/test.csv

  stage_2_processing:
    cmd: python src/components/4_stage_2_preprocessing.py
    deps:
      - src/components/3_data_split.py
      - artifacts/data/train_test/train.csv
      - artifacts/data/train_test/test.csv
    # outs: 
    #   - artifacts/data/processed/stage_2_processing/processed_train_data.csv
    #   - artifacts/data/processed/stage_2_processing/processed_test_data.csv

  model_trainer:
    cmd: python src/components/5_model_training.py
    deps:
      - src/components/4_stage_2_preprocessing.py
      - artifacts/data/processed/stage_2_processing/processed_train_data.csv
      - artifacts/data/processed/stage_2_processing/processed_test_data.csv

  # test_data_prediction:
  #   cmd: python src/components/7_original_testdata_prediction.py
  #   deps:
  #     - src/components/5_model_training.py
  #     - artifacts/model/model.joblib
  #     - artifacts/preprocessor/preprocessor.joblib
  #     - artifacts/data/processed/stage_1_processing/preprocessed_test_data.csv

