Voting_Classifier:
    Best_Cost: 1970.0
    Fittable_Params:
        estimators:
        - !!python/tuple
            - SGD_Classifier
            - !!python/object:sklearn.linear_model._stochastic_gradient.SGDClassifier
                C: 1.0
                _sklearn_version: 1.3.2
                alpha: 0.0001
                average: false
                class_weight: null
                early_stopping: false
                epsilon: 0.1
                eta0: 0.0
                fit_intercept: true
                l1_ratio: 0.15
                learning_rate: optimal
                loss: perceptron
                max_iter: 1000
                n_iter_no_change: 5
                n_jobs: null
                penalty: l2
                power_t: 0.5
                random_state: null
                shuffle: true
                tol: 0.001
                validation_fraction: 0.1
                verbose: 0
                warm_start: false
        - !!python/tuple
            - MLP_Classifier
            - !!python/object:sklearn.neural_network._multilayer_perceptron.MLPClassifier
                _sklearn_version: 1.3.2
                activation: identity
                alpha: 0.0001
                batch_size: auto
                beta_1: 0.9
                beta_2: 0.999
                early_stopping: false
                epsilon: 1.0e-08
                hidden_layer_sizes: !!python/tuple
                - 1500
                - 800
                - 400
                - 200
                learning_rate: constant
                learning_rate_init: 0.001
                loss: log_loss
                max_fun: 15000
                max_iter: 310
                momentum: 0.9
                n_iter_no_change: 10
                nesterovs_momentum: true
                power_t: 0.5
                random_state: null
                shuffle: true
                solver: adam
                tol: 0.0001
                validation_fraction: 0.1
                verbose: false
                warm_start: false
        - !!python/tuple
            - XGB_Classifier
            - !!python/object:xgboost.sklearn.XGBClassifier
                base_score: null
                booster: gbtree
                callbacks: null
                colsample_bylevel: null
                colsample_bynode: null
                colsample_bytree: null
                device: null
                early_stopping_rounds: null
                enable_categorical: false
                eval_metric: null
                feature_types: null
                gamma: null
                grow_policy: null
                importance_type: null
                interaction_constraints: null
                learning_rate: 6.870805859249905
                max_bin: null
                max_cat_threshold: null
                max_cat_to_onehot: null
                max_delta_step: null
                max_depth: null
                max_leaves: null
                min_child_weight: null
                missing: .nan
                monotone_constraints: null
                multi_strategy: null
                n_estimators: 842
                n_jobs: null
                num_parallel_tree: null
                objective: binary:logistic
                random_state: null
                reg_alpha: null
                reg_lambda: null
                sampling_method: null
                scale_pos_weight: null
                subsample: null
                tree_method: approx
                validate_parameters: null
                verbosity: null
        - !!python/tuple
            - Grad_Boost
            - !!python/object:sklearn.ensemble._gb.GradientBoostingClassifier
                _sklearn_version: 1.3.2
                alpha: 0.9
                ccp_alpha: 0.0
                criterion: friedman_mse
                init: null
                learning_rate: 0.1
                loss: exponential
                max_depth: 3
                max_features: log2
                max_leaf_nodes: null
                min_impurity_decrease: 0.0
                min_samples_leaf: 1
                min_samples_split: 2
                min_weight_fraction_leaf: 0.0
                n_estimators: 100
                n_iter_no_change: null
                random_state: null
                subsample: 1.0
                tol: 0.0001
                validation_fraction: 0.1
                verbose: 0
                warm_start: false
        - !!python/tuple
            - Logistic_Regression
            - !!python/object:sklearn.linear_model._logistic.LogisticRegression
                C: 1.0
                _sklearn_version: 1.3.2
                class_weight: null
                dual: false
                fit_intercept: true
                intercept_scaling: 1
                l1_ratio: null
                max_iter: 100
                multi_class: auto
                n_jobs: null
                penalty: l2
                random_state: null
                solver: lbfgs
                tol: 0.0001
                verbose: 0
                warm_start: false
        - !!python/tuple
            - Hist_Grad_Boost_Classifier
            - !!python/object:sklearn.ensemble._hist_gradient_boosting.gradient_boosting.HistGradientBoostingClassifier
                _sklearn_version: 1.3.2
                categorical_features: null
                class_weight: null
                early_stopping: auto
                interaction_cst: null
                l2_regularization: 0.0
                learning_rate: 0.1
                loss: log_loss
                max_bins: 255
                max_depth: null
                max_iter: 125
                max_leaf_nodes: 31
                min_samples_leaf: 20
                monotonic_cst: null
                n_iter_no_change: 10
                random_state: null
                scoring: loss
                tol: 1.0e-07
                validation_fraction: 0.1
                verbose: 0
                warm_start: false
        - !!python/tuple
            - Random Forest
            - !!python/object:sklearn.ensemble._forest.RandomForestClassifier
                _sklearn_version: 1.3.2
                base_estimator: deprecated
                bootstrap: true
                ccp_alpha: 0.0
                class_weight: balanced
                criterion: entropy
                estimator: !!python/object:sklearn.tree._classes.DecisionTreeClassifier
                    _sklearn_version: 1.3.2
                    ccp_alpha: 0.0
                    class_weight: null
                    criterion: gini
                    max_depth: null
                    max_features: null
                    max_leaf_nodes: null
                    min_impurity_decrease: 0.0
                    min_samples_leaf: 1
                    min_samples_split: 2
                    min_weight_fraction_leaf: 0.0
                    random_state: null
                    splitter: best
                estimator_params: !!python/tuple
                - criterion
                - max_depth
                - min_samples_split
                - min_samples_leaf
                - min_weight_fraction_leaf
                - max_features
                - max_leaf_nodes
                - min_impurity_decrease
                - random_state
                - ccp_alpha
                max_depth: null
                max_features: sqrt
                max_leaf_nodes: null
                max_samples: null
                min_impurity_decrease: 0.0
                min_samples_leaf: 1
                min_samples_split: 2
                min_weight_fraction_leaf: 0.0
                n_estimators: 140
                n_jobs: null
                oob_score: false
                random_state: null
                verbose: 0
                warm_start: false
        n_jobs: -1
        voting: hard
        weights: null
