Ada_Boost:
    Best_Cost: 38520
    Fittable_Params: &id001
        algorithm: SAMME
        n_estimators: 109
    HyperOpt:
        Cost: 38520
        params: *id001
    Optuna:
        Cost: 42520.0
        params:
            algorithm: SAMME
            n_estimators: 146
Bagging_Classifier:
    Best_Cost: 33060
    Fittable_Params: &id002
        n_estimators: 65
    HyperOpt:
        Cost: 33060
        params: *id002
    Optuna:
        Cost: 44060.0
        params:
            n_estimators: 73
Decision_Tree_Classifier:
    Best_Cost: 48060
    Fittable_Params: &id003
        criterion: gini
        max_features: null
        splitter: best
    HyperOpt:
        Cost: 48060
        params: *id003
    Optuna:
        Cost: 76060.0
        params:
            criterion: entropy
            max_features: null
            splitter: best
ExtraTreesClassifier:
    Best_Cost: 50050
    Fittable_Params: &id004
        class_weight: balanced
        criterion: gini
        max_features: log2
        n_estimators: 882
    HyperOpt:
        Cost: 50050
        params: *id004
    Optuna:
        Cost: 55530.0
        params:
            class_weight: balanced
            criterion: gini
            max_features: sqrt
            n_estimators: 319
Grad_Boost:
    Best_Cost: 44060
    Fittable_Params: &id005
        criterion: squared_error
        loss: log_loss
        max_features: null
        n_estimators: 134
    HyperOpt:
        Cost: 44060
        params: *id005
    Optuna:
        Cost: 44560.0
        params:
            criterion: squared_error
            loss: exponential
            max_features: null
            n_estimators: 107
Hist_Grad_Boost_Classifier:
    Best_Cost: 31030.0
    Fittable_Params: &id006
        max_iter: 534
    HyperOpt:
        Cost: 31030
        params:
            max_iter: 751
    Optuna:
        Cost: 31030.0
        params: *id006
KNN_Classifier:
    Best_Cost: 53210.0
    Fittable_Params: &id007
        algorithm: brute
        n_neighbors: 11
        weights: uniform
    HyperOpt:
        Cost: 56180
        params:
            algorithm: brute
            n_neighbors: 8
            weights: uniform
    Optuna:
        Cost: 53210.0
        params: *id007
Logistic_Regression:
    Best_Cost: 88860.0
    Fittable_Params: &id008
        penalty: null
    HyperOpt:
        Cost: 88860
        params:
            penalty: null
    Optuna:
        Cost: 88860.0
        params: *id008
Random Forest:
    Best_Cost: 50050.0
    Fittable_Params: &id009
        class_weight: balanced_subsample
        criterion: log_loss
        max_features: log2
        n_estimators: 124
    HyperOpt:
        Cost: 50540
        params:
            class_weight: balanced
            criterion: gini
            max_features: log2
            n_estimators: 119
    Optuna:
        Cost: 50050.0
        params: *id009
SGD_Classifier:
    Best_Cost: 3480
    Fittable_Params: &id010
        loss: squared_error
    HyperOpt:
        Cost: 3480
        params: *id010
    Optuna:
        Cost: 29680.0
        params:
            loss: epsilon_insensitive
Stacked_Classifier:
    Ada_Boost:
        algorithm: SAMME
        base_estimator: deprecated
        estimator: null
        learning_rate: 1.0
        n_estimators: 109
        random_state: null
    Bagging_Classifier:
        base_estimator: deprecated
        bootstrap: true
        bootstrap_features: false
        estimator: null
        max_features: 1.0
        max_samples: 1.0
        n_estimators: 65
        n_jobs: null
        oob_score: false
        random_state: null
        verbose: 0
        warm_start: false
    Best_Cost: 43560.0
    Decision_Tree_Classifier:
        ccp_alpha: 0.0
        class_weight: null
        criterion: gini
        max_depth: null
        max_features: null
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0.0
        random_state: null
        splitter: best
    Fittable_Params: &id011
        cv: 5
        estimators: &id012
        - !!python/tuple
            - SGD_Classifier
            - !!python/object:sklearn.linear_model._stochastic_gradient.SGDClassifier
                C: 1.0
                _sklearn_version: 1.3.2
                alpha: 0.0001
                average: false
                class_weight: null
                early_stopping: false
                epsilon: 0.1
                eta0: 0.0
                fit_intercept: true
                l1_ratio: 0.15
                learning_rate: optimal
                loss: squared_error
                max_iter: 1000
                n_iter_no_change: 5
                n_jobs: null
                penalty: l2
                power_t: 0.5
                random_state: null
                shuffle: true
                tol: 0.001
                validation_fraction: 0.1
                verbose: 0
                warm_start: false
        - !!python/tuple
            - XGB_Classifier
            - !!python/object:xgboost.sklearn.XGBClassifier
                base_score: null
                booster: gbtree
                callbacks: null
                colsample_bylevel: null
                colsample_bynode: null
                colsample_bytree: null
                device: null
                early_stopping_rounds: null
                enable_categorical: false
                eval_metric: null
                feature_types: null
                gamma: null
                grow_policy: null
                importance_type: null
                interaction_constraints: null
                learning_rate: 3.6523285164797543
                max_bin: null
                max_cat_threshold: null
                max_cat_to_onehot: null
                max_delta_step: null
                max_depth: null
                max_leaves: null
                min_child_weight: null
                missing: .nan
                monotone_constraints: null
                multi_strategy: null
                n_estimators: 829
                n_jobs: null
                num_parallel_tree: null
                objective: binary:logistic
                random_state: null
                reg_alpha: null
                reg_lambda: null
                sampling_method: null
                scale_pos_weight: null
                subsample: null
                tree_method: hist
                validate_parameters: null
                verbosity: null
        - !!python/tuple
            - Hist_Grad_Boost_Classifier
            - !!python/object:sklearn.ensemble._hist_gradient_boosting.gradient_boosting.HistGradientBoostingClassifier
                _sklearn_version: 1.3.2
                categorical_features: null
                class_weight: null
                early_stopping: auto
                interaction_cst: null
                l2_regularization: 0.0
                learning_rate: 0.1
                loss: log_loss
                max_bins: 255
                max_depth: null
                max_iter: 534
                max_leaf_nodes: 31
                min_samples_leaf: 20
                monotonic_cst: null
                n_iter_no_change: 10
                random_state: null
                scoring: loss
                tol: 1.0e-07
                validation_fraction: 0.1
                verbose: 0
                warm_start: false
        - !!python/tuple
            - Bagging_Classifier
            - !!python/object:sklearn.ensemble._bagging.BaggingClassifier
                _sklearn_version: 1.3.2
                base_estimator: deprecated
                bootstrap: true
                bootstrap_features: false
                estimator: null
                estimator_params: !!python/tuple []
                max_features: 1.0
                max_samples: 1.0
                n_estimators: 65
                n_jobs: null
                oob_score: false
                random_state: null
                verbose: 0
                warm_start: false
        - !!python/tuple
            - Ada_Boost
            - !!python/object:sklearn.ensemble._weight_boosting.AdaBoostClassifier
                _sklearn_version: 1.3.2
                algorithm: SAMME
                base_estimator: deprecated
                estimator: null
                estimator_params: !!python/tuple []
                learning_rate: 1.0
                n_estimators: 109
                random_state: null
        - !!python/tuple
            - Grad_Boost
            - !!python/object:sklearn.ensemble._gb.GradientBoostingClassifier
                _sklearn_version: 1.3.2
                alpha: 0.9
                ccp_alpha: 0.0
                criterion: squared_error
                init: null
                learning_rate: 0.1
                loss: log_loss
                max_depth: 3
                max_features: null
                max_leaf_nodes: null
                min_impurity_decrease: 0.0
                min_samples_leaf: 1
                min_samples_split: 2
                min_weight_fraction_leaf: 0.0
                n_estimators: 134
                n_iter_no_change: null
                random_state: null
                subsample: 1.0
                tol: 0.0001
                validation_fraction: 0.1
                verbose: 0
                warm_start: false
        - !!python/tuple
            - Decision_Tree_Classifier
            - !!python/object:sklearn.tree._classes.DecisionTreeClassifier
                _sklearn_version: 1.3.2
                ccp_alpha: 0.0
                class_weight: null
                criterion: gini
                max_depth: null
                max_features: null
                max_leaf_nodes: null
                min_impurity_decrease: 0.0
                min_samples_leaf: 1
                min_samples_split: 2
                min_weight_fraction_leaf: 0.0
                random_state: null
                splitter: best
        final_estimator: !!python/object:sklearn.linear_model._stochastic_gradient.SGDClassifier
            C: 1.0
            _sklearn_version: 1.3.2
            alpha: 0.0001
            average: false
            class_weight: null
            early_stopping: false
            epsilon: 0.1
            eta0: 0.0
            fit_intercept: true
            l1_ratio: 0.15
            learning_rate: optimal
            loss: squared_error
            max_iter: 1000
            n_iter_no_change: 5
            n_jobs: null
            penalty: l2
            power_t: 0.5
            random_state: null
            shuffle: true
            tol: 0.001
            validation_fraction: 0.1
            verbose: 0
            warm_start: false
        n_jobs: -1
        passthrough: false
        stack_method: predict
    Grad_Boost:
        ccp_alpha: 0.0
        criterion: squared_error
        init: null
        learning_rate: 0.1
        loss: log_loss
        max_depth: 3
        max_features: null
        max_leaf_nodes: null
        min_impurity_decrease: 0.0
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0.0
        n_estimators: 134
        n_iter_no_change: null
        random_state: null
        subsample: 1.0
        tol: 0.0001
        validation_fraction: 0.1
        verbose: 0
        warm_start: false
    Hist_Grad_Boost_Classifier:
        categorical_features: null
        class_weight: null
        early_stopping: auto
        interaction_cst: null
        l2_regularization: 0.0
        learning_rate: 0.1
        loss: log_loss
        max_bins: 255
        max_depth: null
        max_iter: 534
        max_leaf_nodes: 31
        min_samples_leaf: 20
        monotonic_cst: null
        n_iter_no_change: 10
        random_state: null
        scoring: loss
        tol: 1.0e-07
        validation_fraction: 0.1
        verbose: 0
        warm_start: false
    HyperOpt:
        Cost: 148660
        params:
            passthrough: true
            stack_method: auto
    Optuna:
        Cost: 43560.0
        params: *id011
    SGD_Classifier:
        alpha: 0.0001
        average: false
        class_weight: null
        early_stopping: false
        epsilon: 0.1
        eta0: 0.0
        fit_intercept: true
        l1_ratio: 0.15
        learning_rate: optimal
        loss: squared_error
        max_iter: 1000
        n_iter_no_change: 5
        n_jobs: null
        penalty: l2
        power_t: 0.5
        random_state: null
        shuffle: true
        tol: 0.001
        validation_fraction: 0.1
        verbose: 0
        warm_start: false
    XGB_Classifier:
        base_score: null
        booster: gbtree
        callbacks: null
        colsample_bylevel: null
        colsample_bynode: null
        colsample_bytree: null
        device: null
        early_stopping_rounds: null
        enable_categorical: false
        eval_metric: null
        feature_types: null
        gamma: null
        grow_policy: null
        importance_type: null
        interaction_constraints: null
        learning_rate: 3.6523285164797543
        max_bin: null
        max_cat_threshold: null
        max_cat_to_onehot: null
        max_delta_step: null
        max_depth: null
        max_leaves: null
        min_child_weight: null
        missing: .nan
        monotone_constraints: null
        multi_strategy: null
        n_estimators: 829
        n_jobs: null
        num_parallel_tree: null
        objective: binary:logistic
        random_state: null
        reg_alpha: null
        reg_lambda: null
        sampling_method: null
        scale_pos_weight: null
        subsample: null
        tree_method: hist
        validate_parameters: null
        verbosity: null
Voting_Classifier:
    Best_Cost: 35550.0
    Fittable_Params:
        estimators: *id012
        n_jobs: -1
        voting: hard
        weights: null
XGB_Classifier:
    Best_Cost: 8070.0
    Fittable_Params: &id013
        booster: gbtree
        learning_rate: 3.6523285164797543
        n_estimators: 829
        tree_method: hist
    HyperOpt:
        Cost: 19450
        params:
            booster: gbtree
            learning_rate: 7.3257095633559
            n_estimators: 130
            tree_method: approx
    Optuna:
        Cost: 8070.0
        params: *id013
