artifacts_root: 'artifacts'

data_ingestion_config:
  train_data1:
    secure_connect_bundle: Secrets/Bundles/secure-connect-scania-truck-failure-1.zip
    token: Secrets/Tokens/scania_truck_failure_1-token.json
    key_space_train_data_1: scania_truck_failure1
    table_train_data_1: train_data1
    path: /workspaces/scania_failures_2/artifacts/data/raw/train_data_1.csv

  train_data2:
    secure_connect_bundle: Secrets/Bundles/secure-connect-scania-truck-failure-train-2.zip
    token: Secrets/Tokens/scania_truck_failure_train_2-token.json
    key_space_train_data_2: scania_truck_failure_train2
    table_train_data_2: train_data2
    path: /workspaces/scania_failures_2/artifacts/data/raw/train_data_2.csv

  train_data3:
    secure_connect_bundle: Secrets/Bundles/secure-connect-scania-truck-failure-train-3.zip
    token: Secrets/Tokens/scania_truck_failure_train_3-token.json
    key_space_train_data_3: scania_truck_failure_train3
    table_train_data_3: train_data3
    path: /workspaces/scania_failures_2/artifacts/data/raw/train_data_3.csv

  test_data1:
    secure_connect_bundle: Secrets/Bundles/Test Data Bundles/secure-connect-scania-truck-failure-test1.zip
    token: Secrets/Tokens/Test Data Tokens/scania_truck_failure_test1-token.json
    key_space_test_data_1: scania_truck_failure_test_1
    table_test_data_1: test_data1
    path: /workspaces/scania_failures_2/artifacts/data/raw/test_data_1.csv

  test_data2:
    secure_connect_bundle: Secrets/Bundles/Test Data Bundles/secure-connect-scania-truck-failure-test2.zip
    token: Secrets/Tokens/Test Data Tokens/scania_truck_failure_test2-token.json
    key_space_test_data_2: scania_truck_failure_test_2
    table_test_data_2: test_data2
    path: /workspaces/scania_failures_2/artifacts/data/raw/test_data_2.csv

  test_data3:
    secure_connect_bundle: Secrets/Bundles/Test Data Bundles/secure-connect-scania-truck-failure-test3.zip
    token: Secrets/Tokens/Test Data Tokens/scania_truck_failure_test3-token.json
    key_space_test_data_3: scania_truck_failure_test_3
    table_test_data_3: test_data3
    path: /workspaces/scania_failures_2/artifacts/data/raw/test_data_3.csv
  root_dir: /workspaces/scania_failures_2/artifacts/data/raw

data_path_config:
  train_data1: /workspaces/scania_failures_2/artifacts/data/raw/train_data_1.csv
  train_data2: /workspaces/scania_failures_2/artifacts/data/raw/train_data_2.csv
  train_data3: /workspaces/scania_failures_2/artifacts/data/raw/train_data_3.csv
  test_data1: /workspaces/scania_failures_2/artifacts/data/raw/test_data_1.csv
  test_data2: /workspaces/scania_failures_2/artifacts/data/raw/test_data_2.csv
  test_data3: /workspaces/scania_failures_2/artifacts/data/raw/test_data_3.csv
  
data_stage_1_processing_config:
  root_dir: '/workspaces/scania_failures_2/artifacts/data/processed/stage_1_processing'
  train_data_path: '/workspaces/scania_failures_2/artifacts/data/processed/stage_1_processing/preprocessed_train_data.csv'
  test_data_path: '/workspaces/scania_failures_2/artifacts/data/processed/stage_1_processing/preprocessed_test_data.csv'

data_stage_2_processing_config:
  root_dir: '/workspaces/scania_failures_2/artifacts/data/processed/stage_2_processing'
  train_data_path: '/workspaces/scania_failures_2/artifacts/data/processed/stage_2_processing/processed_train_data.csv'
  test_data_path: '/workspaces/scania_failures_2/artifacts/data/processed/stage_2_processing/processed_test_data.csv'

data_split_config:
  root_dir: '/workspaces/scania_failures_2/artifacts/data/train_test'
  train_batch_path: '/workspaces/scania_failures_2/artifacts/data/train_test/train.csv'
  test_batch_path: '/workspaces/scania_failures_2/artifacts/data/train_test/test.csv'

model_trainer:
  root_dir: '/workspaces/scania_failures_2/artifacts/model'
  model_path: '/workspaces/scania_failures_2/artifacts/model/model.joblib'

model_metrics:
  root_dir: /workspaces/scania_failures_2/artifacts/metrics
  metrics: /workspaces/scania_failures_2/artifacts/metrics/metrics.yaml
  best_metric: /workspaces/scania_failures_2/artifacts/metrics/best_metric.yaml

preprocessor:
  root_dir: '/workspaces/scania_failures_2/artifacts/preprocessor'
  preprocessor_path: '/workspaces/scania_failures_2/artifacts/preprocessor/preprocessor.joblib'








