GITHUB_USERNAME: gAAAAABl2g6AIua_QPNTzHQ8LwykM7_Rvyp9RiJQ30fi_wDadXu_FJCxo6nVORCp1-1NdrKNiqTm2M0r0p7xyPRoQbf8KP4Z2Q==
PAT: gAAAAABl2g6AtxT3ncZ1JoB7zlFNlsOz05OHtmy1wl8cBrp1PjCc4w1C5npsA0Cw0Efk2yaOhNlBCIxxnoQibuT-r5UI4KqDbgHx1ZHcsbopvjnvBMfwS5KKCAoIDGdW3qTyMcPTFT95
REPO_NAME: gAAAAABl2g6AZLfnNwZZSrwHpQDgDPi5QuyS8vMr49ekKdpkGuEuCLqgzpr6kdTBTgS4JPWlm6CIg5LLAy5RcQbQvSqsL_obkQ==
